#!/bin/bash

export LC_ALL=C

#git submodule deinit --all -f
docker run --rm \
  -e RUN_LOCAL=true \
  -w /tmp/lint \
  -v "$(git rev-parse --show-toplevel)":/tmp/lint oxsecurity/megalinter-cupcake:latest
