BASH_SHFMT_ARGUMENTS: "-i 2 -ci"
DISABLE_ERRORS_LINTERS: COPYPASTE_JSCPD,REPOSITORY_KICS,REPOSITORY_CHECKOV,REPOSITORY_TRIVY,SPELL_CSPELL
DISABLE_LINTERS: PYTHON_PYLINT,PYTHON_PYRIGHT,PYTHON_RUFF,PYTHON_MYPY,YAML_V8R,TYPESCRIPT_STANDARD
ENABLE: ACTION,BASH,DOCKERFILE,JSON,MAKEFILE,MARKDOWN,PYTHON,REPOSITORY,COPYPASTE,SPELL,YAML,TYPESCRIPT,JAVASCRIPT
EXCLUDED_DIRECTORIES: models,.venv
LINTER_RULES_PATH: /
LOG_LEVEL: NOTICE
REPORT_OUTPUT_FOLDER: megalinter-reports
