ENABLE: ACTION,BASH,DOCKERFILE,JSON,MAKEFILE,MARKDOWN,PYTHON
DISABLE_LINTERS: PYTHON_PYLINT,PYTHON_PYRIGHT,PYTHON_RUFF,PYTHON_MYPY
EXCLUDED_DIRECTORIES: models,.venv
LINTER_RULES_PATH: /
LOG_LEVEL: NOTICE
REPORT_OUTPUT_FOLDER: megalinter-reports
BASH_SHFMT_ARGUMENTS: "-i 2 -ci"

