jobs:
  reformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          architecture: 'x64'
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install black isort yq autoflake
      - name: autoflake
        run: autoflake --in-place --expand-star-imports --remove-all-unused-imports --ignore-init-module-imports --recursive .
      - name: isort
        run: isort .
      - name: black
        run: black .
      - name: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto Formatting
          commit_options: '--no-verify --signoff'
          commit_user_name: gitHub gctions auto-formatting bot
name: reformat
'on': [push, workflow_dispatch, pull_request]
